import logging


class Config:
    FILE_LOGGING_LEVEL = logging.DEBUG
    CONSOLE_LOGGING_LEVEL = logging.INFO
    LOG_FILENAME = 'cybercloud.log'

    # Threads count
    THREADS_COUNT = 1
    MAX_THREAD_COUNT = 1

    # Stopwords
    ADDITIONAL_STOPWORDS = {'will', 'security', 'access', 'source', 'now', 'application', 'technical', 'document',
                            'attack', 'comment', 'used', 'think', 'list', 'start', 'editor', 'displayed', 'management',
                            'implemented', 'implement', 'their', 'own', 'has', 'also', 'this', 'need', 'reachable',
                            'usable', 'in', 'feature', 'detail', 'us', 'circumstance', 'presented', 'gather',
                            'gathered',
                            'present', 'several', 'first', 'share', 'good', 'side', 'issue', 'something', 'result',
                            'change',
                            'following', 'much', 'instead', 'one', 'may', 'board', 'post', 'useful', 'often', 'still',
                            'via',
                            'thing', 'instead', 'see', 'reply', 'pm', 'am', 'write', 'day', 'object', 'message',
                            'messages',
                            'comments', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'yes',
                            'attacker', 'user', 'different', 'multiple', 'server', 'part', 'require', 'example', 'name',
                            'cisa',
                            'use', 'another', 'help', 'https', 'take', 'create', 'without', 'even', 'blog', 'related',
                            'using',
                            'new', 'client', 'report', 'service', 'case', 'march', 'report', 'new', 'possible',
                            'contain', 'long', 'sit', 'parameter', 'details', 'page', 'open', 'back', 'indicate',
                            'give',
                            'article', 'running', 'many', 'microsoft', 'uses', 'called', 'read', 'update', 'content',
                            'able', 'accepting',
                            'accomplishments', 'activities', 'actual', 'actually', 'added', 'addition', 'adress',
                            'adults', 'advertisement', 'ago', 'agree', 'allow', 'allows', 'already', 'although',
                            'always', 'among', 'amount',
                            'analyzed', 'angry', 'anuj', 'anyone', 'anything', 'appears', 'apple', 'approximately',
                            'around', 'asb', 'ask',
                            'assist', 'assume', 'assumed', 'attach', 'attacked', 'author', 'avoid', 'based',
                            'basically', 'beat', 'begun',
                            'behave', 'behind', 'believe', 'benefit', 'best', 'better', 'big', 'biggest', 'bit', 'body',
                            'brian', 'brian’s',
                            'briankrebs', 'broader', 'brown', 'buffers', 'business', 'businesses', 'buy', 'call',
                            'can’t', 'care', 'cause',
                            'certainly', 'certs', 'challenge', 'changed', 'check', 'click', 'closed', 'come', 'coming',
                            'company',
                            'compassionately', 'compete', 'competitor', 'computer', 'computers', 'consequence',
                            'constantly', 'contact',
                            'continue', 'contribute', 'control', 'cost', 'countries', 'couple', 'cover', 'criticise',
                            'current', 'currently',
                            'customers', 'cut', 'cyber', 'cybersecurity', 'cyberspace', 'daily', 'danger', 'date',
                            'dave', 'death', 'deciding',
                            'decision', 'decline', 'declined', 'definitely', 'depend', 'derec', 'designed', 'desires',
                            'devote', 'difficult',
                            'difficulty', 'directly', 'director', 'discovered', 'diss', 'diverse', 'diversified',
                            'documented', 'doesn’t',
                            'don’t', 'donate', 'donated', 'donating', 'done', 'drinking', 'drive', 'drives', 'easy',
                            'effective',
                            'effectively', 'effort', 'efforts', 'either', 'em', 'email', 'emasculating', 'emergency',
                            'enabling', 'end',
                            'enforcement', 'engineer', 'ensuring', 'entire', 'entry', 'essential', 'etc', 'eternally',
                            'every', 'everyone',
                            'everything', 'exactly', 'examined', 'excellent', 'exist', 'exp', 'expect', 'explained',
                            'explanation', 'explore',
                            'exploring', 'extended', 'extremely', 'far', 'favorable', 'feed', 'feeds', 'file', 'filed',
                            'financial', 'find',
                            'finding', 'flowing', 'focus', 'follow', 'followed', 'forced', 'forward', 'free',
                            'frequently', 'full', 'fully',
                            'fund', 'fundamentally', 'funded', 'funding', 'funds', 'funny', 'future', 'generous',
                            'gets', 'getting', 'giving',
                            'glad', 'go', 'go…', 'going', 'got', 'gotten', 'grateful', 'greets', 'group', 'grow',
                            'growing', 'growth', 'hand',
                            'handle', 'hands', 'hang', 'happening', 'happy', 'hard', 'he’s', 'heads', 'healing',
                            'hearing', 'helping', 'helps',
                            'hey', 'hi', 'higher', 'highly', 'history', 'hit', 'hope', 'hopefully', 'house', 'huge',
                            'i’d', 'i’ll', 'i’m',
                            'i’ve', 'ian', 'idea', 'ideally', 'identify', 'ie', 'image', 'imagine', 'immediately',
                            'implementing', 'important',
                            'inc', 'including', 'income', 'indiscriminately', 'inevitable', 'information', 'infosec',
                            'inside', 'installed',
                            'instrumental', 'intelligent', 'intend', 'interest', 'interested', 'interests',
                            'interventions', 'investment',
                            'involvement', 'involving', 'ip', 'isps', 'it’s', 'join', 'joint', 'jon', 'keep', 'keeping',
                            'key', 'kind', 'knew',
                            'know', 'knowing', 'knows', 'krebs', 'krebs’s', 'large', 'largest', 'last', 'lay', 'le',
                            'let', 'level', 'levels',
                            'lift', 'likely', 'little', 'longer', 'longtime', 'look', 'lose', 'lost', 'lot', 'lots',
                            'made', 'main',
                            'maintain', 'make', 'manage', 'mark', 'match', 'maybe', 'mean', 'means', 'men', 'mention',
                            'moderate', 'monday',
                            'month', 'months', 'move', 'moving', 'mr', 'needed', 'needs', 'network', 'network’s',
                            'networking', 'never',
                            'no…the', 'none', 'nope', 'notify', 'obtain', 'obviously', 'occurrence', 'online',
                            'operate', 'operations',
                            'opportunities', 'opted', 'options', 'orders', 'others', 'partner', 'pc', 'people',
                            'percentage', 'perfect',
                            'perhaps', 'persons', 'pick', 'pings', 'pitch', 'place', 'plan', 'planned', 'please',
                            'plight', 'point', 'pond',
                            'popular', 'position', 'posted', 'posts', 'potentially', 'powered', 'powering', 'pr',
                            'practices', 'pretty',
                            'prevent', 'primarily', 'primary', 'priorities', 'probably', 'problem', 'probly', 'product',
                            'products',
                            'professionals', 'profit', 'program', 'progressive', 'project', 'protected', 'proud',
                            'proves', 'provide',
                            'provides', 'providing', 'push', 'pushing', 'questions', 'quietly', 'raise', 'rates',
                            'realistic', 'realize',
                            'really', 'reasons', 'receive', 'recent', 'recently', 'reckons', 'references', 'relying',
                            'remember', 'remind',
                            'reports', 'required', 'requires', 'reserve', 'return', 'road', 'rock', 'role', 'rules',
                            'rules…', 'run', 'safer',
                            'safety', 'said', 'satisfying', 'say', 'saying', 'says', 'secure', 'seek', 'seems', 'seen',
                            'self', 'sell', 'send',
                            'sent', 'servers', 'serves', 'services', 'set', 'shame', 'shop', 'short', 'show',
                            'shuttered', 'sign', 'silly',
                            'similar', 'simply', 'single', 'sipping', 'site', 'situation', 'skills', 'small',
                            'solution', 'solve', 'somebody',
                            'someone', 'somewhere', 'soon', 'sort', 'sources', 'spare', 'spend', 'sponsors', 'staff',
                            'stance', 'started',
                            'statement', 'status', 'step', 'stop', 'strings', 'stuck', 'style', 'subscribe', 'suddenly',
                            'suggesting',
                            'support', 'supporter', 'supporting', 'supports', 'supposed', 'sure', 'surely', 'survive',
                            'system', 'systems',
                            'takes', 'team', 'teams', 'technology', 'temporary', 'ten', 'thank', 'thanks', 'that’s',
                            'them…', 'them…”',
                            'there’s', 'they’re', 'they’ve', 'things', 'thinking', 'this…a', 'thought', 'thus', 'thx',
                            'time', 'times',
                            'today', 'together', 'told', 'took', 'tools', 'total', 'trashed', 'try', 'twice',
                            'typically', 'unblinking',
                            'understand', 'undoubtedly', 'unexpectedly', 'unfortunate', 'urgent', 'usual', 'wall',
                            'warm', 'way', 'well',
                            'who’s', 'willing', 'won’t', 'work', 'works', 'worse', 'worth', 'worthy', 'wouldn’t',
                            'wrest', 'yet', 'you’ll',
                            'you’re', 'session', 'window', 'data', 'shows', 'home', 'news', 'attempt', 'note',
                            'process', 'a', 'abandon', 'ability', 'able', 'abortion', 'about', 'above', 'abroad',
                            'absence', 'absolute', 'absolutely', 'absorb', 'abuse', 'academic', 'accept', 'access',
                            'accident', 'accompany', 'accomplish', 'according', 'account', 'accurate', 'accuse',
                            'achieve', 'achievement', 'acid', 'acknowledge', 'acquire', 'across', 'act', 'action',
                            'activist', 'activity', 'actor', 'actress', 'actual', 'actually', 'ad', 'adapt', 'add',
                            'addition', 'additional', 'address', 'adequate', 'adjust', 'adjustment', 'administration',
                            'administrator', 'admire', 'admission', 'admit', 'adolescent', 'adopt', 'adult', 'advance',
                            'advanced', 'advantage', 'adventure', 'advertising', 'advice', 'advise', 'adviser',
                            'advocate', 'affair', 'affect', 'afford', 'afraid', 'African', 'African-American', 'after',
                            'afternoon', 'again', 'against', 'age', 'agency', 'agenda', 'agent', 'aggressive', 'ago',
                            'agree', 'agreement', 'agricultural', 'ah', 'ahead', 'aid', 'aide', 'AIDS', 'aim', 'air',
                            'aircraft', 'airline', 'airport', 'album', 'alcohol', 'alive', 'all', 'alliance', 'allow',
                            'ally', 'almost', 'alone', 'along', 'already', 'also', 'alter', 'alternative', 'although',
                            'always', 'AM', 'amazing', 'American', 'among', 'amount', 'analysis', 'analyst', 'analyze',
                            'ancient', 'and', 'anger', 'angle', 'angry', 'animal', 'anniversary', 'announce', 'annual',
                            'another', 'answer', 'anticipate', 'anxiety', 'any', 'anybody', 'anymore', 'anyone',
                            'anything', 'anyway', 'anywhere', 'apart', 'apartment', 'apparent', 'apparently', 'appeal',
                            'appear', 'appearance', 'apple', 'application', 'apply', 'appoint', 'appointment',
                            'appreciate', 'approach', 'appropriate', 'approval', 'approve', 'approximately', 'Arab',
                            'architect', 'area', 'argue', 'argument', 'arise', 'arm', 'armed', 'army', 'around',
                            'arrange', 'arrangement', 'arrest', 'arrival', 'arrive', 'art', 'article', 'artist',
                            'artistic', 'as', 'Asian', 'aside', 'ask', 'asleep', 'aspect', 'assault', 'assert',
                            'assess', 'assessment', 'asset', 'assign', 'assignment', 'assist', 'assistance',
                            'assistant', 'associate', 'association', 'assume', 'assumption', 'assure', 'at', 'athlete',
                            'athletic', 'atmosphere', 'attach', 'attack', 'attempt', 'attend', 'attention', 'attitude',
                            'attorney', 'attract', 'attractive', 'attribute', 'audience', 'author', 'authority', 'auto',
                            'available', 'average', 'avoid', 'award', 'aware', 'awareness', 'away', 'awful', 'baby',
                            'back', 'background', 'bad', 'badly', 'bag', 'bake', 'balance', 'ball', 'ban', 'band',
                            'bank', 'bar', 'barely', 'barrel', 'barrier', 'base', 'baseball', 'basic', 'basically',
                            'basis', 'basket', 'basketball', 'bathroom', 'battery', 'battle', 'be', 'beach', 'bean',
                            'bear', 'beat', 'beautiful', 'beauty', 'because', 'become', 'bed', 'bedroom', 'beer',
                            'before', 'begin', 'beginning', 'behavior', 'behind', 'being', 'belief', 'believe', 'bell',
                            'belong', 'below', 'belt', 'bench', 'bend', 'beneath', 'benefit', 'beside', 'besides',
                            'best', 'bet', 'better', 'between', 'beyond', 'Bible', 'big', 'bike', 'bill', 'billion',
                            'bind', 'biological', 'bird', 'birth', 'birthday', 'bit', 'bite', 'black', 'blade', 'blame',
                            'blanket', 'blind', 'block', 'blood', 'blow', 'blue', 'board', 'boat', 'body', 'bomb',
                            'bombing', 'bond', 'bone', 'book', 'boom', 'boot', 'border', 'born', 'borrow', 'boss',
                            'both', 'bother', 'bottle', 'bottom', 'boundary', 'bowl', 'box', 'boy', 'boyfriend',
                            'brain', 'branch', 'brand', 'bread', 'break', 'breakfast', 'breast', 'breath', 'breathe',
                            'brick', 'bridge', 'brief', 'briefly', 'bright', 'brilliant', 'bring', 'British', 'broad',
                            'broken', 'brother', 'brown', 'brush', 'buck', 'budget', 'build', 'building', 'bullet',
                            'bunch', 'burden', 'burn', 'bury', 'bus', 'business', 'busy', 'but', 'butter', 'button',
                            'buy', 'buyer', 'by', 'cabin', 'cabinet', 'cable', 'cake', 'calculate', 'call', 'camera',
                            'camp', 'campaign', 'campus', 'can', 'Canadian', 'cancer', 'candidate', 'cap', 'capability',
                            'capable', 'capacity', 'capital', 'captain', 'capture', 'car', 'carbon', 'card', 'care',
                            'career', 'careful', 'carefully', 'carrier', 'carry', 'case', 'cash', 'cast', 'cat',
                            'catch', 'category', 'Catholic', 'cause', 'ceiling', 'celebrate', 'celebration',
                            'celebrity', 'cell', 'center', 'central', 'century', 'CEO', 'ceremony', 'certain',
                            'certainly', 'chain', 'chair', 'chairman', 'challenge', 'chamber', 'champion',
                            'championship', 'chance', 'change', 'changing', 'channel', 'chapter', 'character',
                            'characteristic', 'characterize', 'charge', 'charity', 'chart', 'chase', 'cheap', 'check',
                            'cheek', 'cheese', 'chef', 'chemical', 'chest', 'chicken', 'chief', 'child', 'childhood',
                            'Chinese', 'chip', 'chocolate', 'choice', 'cholesterol', 'choose', 'Christian', 'Christmas',
                            'church', 'cigarette', 'circle', 'circumstance', 'cite', 'citizen', 'city', 'civil',
                            'civilian', 'claim', 'class', 'classic', 'classroom', 'clean', 'clear', 'clearly', 'client',
                            'climate', 'climb', 'clinic', 'clinical', 'clock', 'close', 'closely', 'closer', 'clothes',
                            'clothing', 'cloud', 'club', 'clue', 'cluster', 'coach', 'coal', 'coalition', 'coast',
                            'coat', 'code', 'coffee', 'cognitive', 'cold', 'collapse', 'colleague', 'collect',
                            'collection', 'collective', 'college', 'colonial', 'color', 'column', 'combination',
                            'combine', 'come', 'comedy', 'comfort', 'comfortable', 'command', 'commander', 'comment',
                            'commercial', 'commission', 'commit', 'commitment', 'committee', 'common', 'communicate',
                            'communication', 'community', 'company', 'compare', 'comparison', 'compete', 'competition',
                            'competitive', 'competitor', 'complain', 'complaint', 'complete', 'completely', 'complex',
                            'complicated', 'component', 'compose', 'composition', 'comprehensive', 'computer',
                            'concentrate', 'concentration', 'concept', 'concern', 'concerned', 'concert', 'conclude',
                            'conclusion', 'concrete', 'condition', 'conduct', 'conference', 'confidence', 'confident',
                            'confirm', 'conflict', 'confront', 'confusion', 'Congress', 'congressional', 'connect',
                            'connection', 'consciousness', 'consensus', 'consequence', 'conservative', 'consider',
                            'considerable', 'consideration', 'consist', 'consistent', 'constant', 'constantly',
                            'constitute', 'constitutional', 'construct', 'construction', 'consultant', 'consume',
                            'consumer', 'consumption', 'contact', 'contain', 'container', 'contemporary', 'content',
                            'contest', 'context', 'continue', 'continued', 'contract', 'contrast', 'contribute',
                            'contribution', 'control', 'controversial', 'controversy', 'convention', 'conventional',
                            'conversation', 'convert', 'conviction', 'convince', 'cook', 'cookie', 'cooking', 'cool',
                            'cooperation', 'cop', 'cope', 'copy', 'core', 'corn', 'corner', 'corporate', 'corporation',
                            'correct', 'correspondent', 'cost', 'cotton', 'couch', 'could', 'council', 'counselor',
                            'count', 'counter', 'country', 'county', 'couple', 'courage', 'course', 'court', 'cousin',
                            'cover', 'coverage', 'cow', 'crack', 'craft', 'crash', 'crazy', 'cream', 'create',
                            'creation', 'creative', 'creature', 'credit', 'crew', 'crime', 'criminal', 'crisis',
                            'criteria', 'critic', 'critical', 'criticism', 'criticize', 'crop', 'cross', 'crowd',
                            'crucial', 'cry', 'cultural', 'culture', 'cup', 'curious', 'current', 'currently',
                            'curriculum', 'custom', 'customer', 'cut', 'cycle', 'dad', 'daily', 'damage', 'dance',
                            'danger', 'dangerous', 'dare', 'dark', 'darkness', 'data', 'date', 'daughter', 'day',
                            'dead', 'deal', 'dealer', 'dear', 'death', 'debate', 'debt', 'decade', 'decide', 'decision',
                            'deck', 'declare', 'decline', 'decrease', 'deep', 'deeply', 'deer', 'defeat', 'defend',
                            'defendant', 'defense', 'defensive', 'deficit', 'define', 'definitely', 'definition',
                            'degree', 'delay', 'deliver', 'delivery', 'demand', 'democracy', 'Democrat', 'democratic',
                            'demonstrate', 'demonstration', 'deny', 'department', 'depend', 'dependent', 'depending',
                            'depict', 'depression', 'depth', 'deputy', 'derive', 'describe', 'description', 'desert',
                            'deserve', 'design', 'designer', 'desire', 'desk', 'desperate', 'despite', 'destroy',
                            'destruction', 'detail', 'detailed', 'detect', 'determine', 'develop', 'developing',
                            'development', 'device', 'devote', 'dialogue', 'die', 'diet', 'differ', 'difference',
                            'different', 'differently', 'difficult', 'difficulty', 'dig', 'digital', 'dimension',
                            'dining', 'dinner', 'direct', 'direction', 'directly', 'director', 'dirt', 'dirty',
                            'disability', 'disagree', 'disappear', 'disaster', 'discipline', 'discourse', 'discover',
                            'discovery', 'discrimination', 'discuss', 'discussion', 'disease', 'dish', 'dismiss',
                            'disorder', 'display', 'dispute', 'distance', 'distant', 'distinct', 'distinction',
                            'distinguish', 'distribute', 'distribution', 'district', 'diverse', 'diversity', 'divide',
                            'division', 'divorce', 'DNA', 'do', 'doctor', 'document', 'dog', 'domestic', 'dominant',
                            'dominate', 'door', 'double', 'doubt', 'down', 'downtown', 'dozen', 'draft', 'drag',
                            'drama', 'dramatic', 'dramatically', 'draw', 'drawing', 'dream', 'dress', 'drink', 'drive',
                            'driver', 'drop', 'drug', 'dry', 'due', 'during', 'dust', 'duty', 'each', 'eager', 'ear',
                            'early', 'earn', 'earnings', 'earth', 'ease', 'easily', 'east', 'eastern', 'easy', 'eat',
                            'economic', 'economics', 'economist', 'economy', 'edge', 'edition', 'editor', 'educate',
                            'education', 'educational', 'educator', 'effect', 'effective', 'effectively', 'efficiency',
                            'efficient', 'effort', 'egg', 'eight', 'either', 'elderly', 'elect', 'election', 'electric',
                            'electricity', 'electronic', 'element', 'elementary', 'eliminate', 'elite', 'else',
                            'elsewhere', 'e-mail', 'embrace', 'emerge', 'emergency', 'emission', 'emotion', 'emotional',
                            'emphasis', 'emphasize', 'employ', 'employee', 'employer', 'employment', 'empty', 'enable',
                            'encounter', 'encourage', 'end', 'enemy', 'energy', 'enforcement', 'engage', 'engine',
                            'engineer', 'engineering', 'English', 'enhance', 'enjoy', 'enormous', 'enough', 'ensure',
                            'enter', 'enterprise', 'entertainment', 'entire', 'entirely', 'entrance', 'entry',
                            'environment', 'environmental', 'episode', 'equal', 'equally', 'equipment', 'era', 'error',
                            'escape', 'especially', 'essay', 'essential', 'essentially', 'establish', 'establishment',
                            'estate', 'estimate', 'etc', 'ethics', 'ethnic', 'European', 'evaluate', 'evaluation',
                            'even', 'evening', 'event', 'eventually', 'ever', 'every', 'everybody', 'everyday',
                            'everyone', 'everything', 'everywhere', 'evidence', 'evolution', 'evolve', 'exact',
                            'exactly', 'examination', 'examine', 'example', 'exceed', 'excellent', 'except',
                            'exception', 'exchange', 'exciting', 'executive', 'exercise', 'exhibit', 'exhibition',
                            'exist', 'existence', 'existing', 'expand', 'expansion', 'expect', 'expectation', 'expense',
                            'expensive', 'experience', 'experiment', 'expert', 'explain', 'explanation', 'explode',
                            'explore', 'explosion', 'expose', 'exposure', 'express', 'expression', 'extend',
                            'extension', 'extensive', 'extent', 'external', 'extra', 'extraordinary', 'extreme',
                            'extremely', 'eye', 'fabric', 'face', 'facility', 'fact', 'factor', 'factory', 'faculty',
                            'fade', 'fail', 'failure', 'fair', 'fairly', 'faith', 'fall', 'false', 'familiar', 'family',
                            'famous', 'fan', 'fantasy', 'far', 'farm', 'farmer', 'fashion', 'fast', 'fat', 'fate',
                            'father', 'fault', 'favor', 'favorite', 'fear', 'feature', 'federal', 'fee', 'feed', 'feel',
                            'feeling', 'fellow', 'female', 'fence', 'few', 'fewer', 'fiber', 'fiction', 'field',
                            'fifteen', 'fifth', 'fifty', 'fight', 'fighter', 'fighting', 'figure', 'file', 'fill',
                            'film', 'final', 'finally', 'finance', 'financial', 'find', 'finding', 'fine', 'finger',
                            'finish', 'fire', 'firm', 'first', 'fish', 'fishing', 'fit', 'fitness', 'five', 'fix',
                            'flag', 'flame', 'flat', 'flavor', 'flee', 'flesh', 'flight', 'float', 'floor', 'flow',
                            'flower', 'fly', 'focus', 'folk', 'follow', 'following', 'food', 'foot', 'football', 'for',
                            'force', 'foreign', 'forest', 'forever', 'forget', 'form', 'formal', 'formation', 'former',
                            'formula', 'forth', 'fortune', 'forward', 'found', 'foundation', 'founder', 'four',
                            'fourth', 'frame', 'framework', 'free', 'freedom', 'freeze', 'French', 'frequency',
                            'frequent', 'frequently', 'fresh', 'friend', 'friendly', 'friendship', 'from', 'front',
                            'fruit', 'frustration', 'fuel', 'full', 'fully', 'fun', 'function', 'fund', 'fundamental',
                            'funding', 'funeral', 'funny', 'furniture', 'furthermore', 'future', 'gain', 'galaxy',
                            'gallery', 'game', 'gang', 'gap', 'garage', 'garden', 'garlic', 'gas', 'gate', 'gather',
                            'gay', 'gaze', 'gear', 'gender', 'gene', 'general', 'generally', 'generate', 'generation',
                            'genetic', 'gentleman', 'gently', 'German', 'gesture', 'get', 'ghost', 'giant', 'gift',
                            'gifted', 'girl', 'girlfriend', 'give', 'given', 'glad', 'glance', 'glass', 'global',
                            'glove', 'go', 'goal', 'God', 'gold', 'golden', 'golf', 'good', 'government', 'governor',
                            'grab', 'grade', 'gradually', 'graduate', 'grain', 'grand', 'grandfather', 'grandmother',
                            'grant', 'grass', 'grave', 'gray', 'great', 'greatest', 'green', 'grocery', 'ground',
                            'group', 'grow', 'growing', 'growth', 'guarantee', 'guard', 'guess', 'guest', 'guide',
                            'guideline', 'guilty', 'gun', 'guy', 'habit', 'habitat', 'hair', 'half', 'hall', 'hand',
                            'handful', 'handle', 'hang', 'happen', 'happy', 'hard', 'hardly', 'hat', 'hate', 'have',
                            'he', 'head', 'headline', 'headquarters', 'health', 'healthy', 'hear', 'hearing', 'heart',
                            'heat', 'heaven', 'heavily', 'heavy', 'heel', 'height', 'helicopter', 'hell', 'hello',
                            'help', 'helpful', 'her', 'here', 'heritage', 'hero', 'herself', 'hey', 'hi', 'hide',
                            'high', 'highlight', 'highly', 'highway', 'hill', 'him', 'himself', 'hip', 'hire', 'his',
                            'historian', 'historic', 'historical', 'history', 'hit', 'hold', 'hole', 'holiday', 'holy',
                            'home', 'homeless', 'honest', 'honey', 'honor', 'hope', 'horizon', 'horror', 'horse',
                            'hospital', 'host', 'hot', 'hotel', 'hour', 'house', 'household', 'housing', 'how',
                            'however', 'huge', 'human', 'humor', 'hundred', 'hungry', 'hunter', 'hunting', 'hurt',
                            'husband', 'hypothesis', 'I', 'ice', 'idea', 'ideal', 'identification', 'identify',
                            'identity', 'ie', 'if', 'ignore', 'ill', 'illegal', 'illness', 'illustrate', 'image',
                            'imagination', 'imagine', 'immediate', 'immediately', 'immigrant', 'immigration', 'impact',
                            'implement', 'implication', 'imply', 'importance', 'important', 'impose', 'impossible',
                            'impress', 'impression', 'impressive', 'improve', 'improvement', 'in', 'incentive',
                            'incident', 'include', 'including', 'income', 'incorporate', 'increase', 'increased',
                            'increasing', 'increasingly', 'incredible', 'indeed', 'independence', 'independent',
                            'index', 'Indian', 'indicate', 'indication', 'individual', 'industrial', 'industry',
                            'infant', 'infection', 'inflation', 'influence', 'inform', 'information', 'ingredient',
                            'initial', 'initially', 'initiative', 'injury', 'inner', 'innocent', 'inquiry', 'inside',
                            'insight', 'insist', 'inspire', 'install', 'instance', 'instead', 'institution',
                            'institutional', 'instruction', 'instructor', 'instrument', 'insurance', 'intellectual',
                            'intelligence', 'intend', 'intense', 'intensity', 'intention', 'interaction', 'interest',
                            'interested', 'interesting', 'internal', 'international', 'Internet', 'interpret',
                            'interpretation', 'intervention', 'interview', 'into', 'introduce', 'introduction',
                            'invasion', 'invest', 'investigate', 'investigation', 'investigator', 'investment',
                            'investor', 'invite', 'involve', 'involved', 'involvement', 'Iraqi', 'Irish', 'iron',
                            'Islamic', 'island', 'Israeli', 'issue', 'it', 'Italian', 'item', 'its', 'itself', 'jacket',
                            'jail', 'Japanese', 'jet', 'Jew', 'Jewish', 'job', 'join', 'joint', 'joke', 'journal',
                            'journalist', 'journey', 'joy', 'judge', 'judgment', 'juice', 'jump', 'junior', 'jury',
                            'just', 'justice', 'justify', 'keep', 'key', 'kick', 'kid', 'kill', 'killer', 'killing',
                            'kind', 'king', 'kiss', 'kitchen', 'knee', 'knife', 'knock', 'know', 'knowledge', 'lab',
                            'label', 'labor', 'laboratory', 'lack', 'lady', 'lake', 'land', 'landscape', 'language',
                            'lap', 'large', 'largely', 'last', 'late', 'later', 'Latin', 'latter', 'laugh', 'launch',
                            'law', 'lawn', 'lawsuit', 'lawyer', 'lay', 'layer', 'lead', 'leader', 'leadership',
                            'leading', 'leaf', 'league', 'lean', 'learn', 'learning', 'least', 'leather', 'leave',
                            'left', 'leg', 'legacy', 'legal', 'legend', 'legislation', 'legitimate', 'lemon', 'length',
                            'less', 'lesson', 'let', 'letter', 'level', 'liberal', 'library', 'license', 'lie', 'life',
                            'lifestyle', 'lifetime', 'lift', 'light', 'like', 'likely', 'limit', 'limitation',
                            'limited', 'line', 'link', 'lip', 'list', 'listen', 'literally', 'literary', 'literature',
                            'little', 'live', 'living', 'load', 'loan', 'local', 'locate', 'location', 'lock', 'long',
                            'long-term', 'look', 'loose', 'lose', 'loss', 'lost', 'lot', 'lots', 'loud', 'love',
                            'lovely', 'lover', 'low', 'lower', 'luck', 'lucky', 'lunch', 'lung', 'machine', 'mad',
                            'magazine', 'mail', 'main', 'mainly', 'maintain', 'maintenance', 'major', 'majority',
                            'make', 'maker', 'makeup', 'male', 'mall', 'man', 'manage', 'management', 'manager',
                            'manner', 'manufacturer', 'manufacturing', 'many', 'map', 'margin', 'mark', 'market',
                            'marketing', 'marriage', 'married', 'marry', 'mask', 'mass', 'massive', 'master', 'match',
                            'material', 'math', 'matter', 'may', 'maybe', 'mayor', 'me', 'meal', 'mean', 'meaning',
                            'meanwhile', 'measure', 'measurement', 'meat', 'mechanism', 'media', 'medical',
                            'medication', 'medicine', 'medium', 'meet', 'meeting', 'member', 'membership', 'memory',
                            'mental', 'mention', 'menu', 'mere', 'merely', 'mess', 'message', 'metal', 'meter',
                            'method', 'Mexican', 'middle', 'might', 'military', 'milk', 'million', 'mind', 'mine',
                            'minister', 'minor', 'minority', 'minute', 'miracle', 'mirror', 'miss', 'missile',
                            'mission', 'mistake', 'mix', 'mixture', 'mm-hmm', 'mode', 'model', 'moderate', 'modern',
                            'modest', 'mom', 'moment', 'money', 'monitor', 'month', 'mood', 'moon', 'moral', 'more',
                            'moreover', 'morning', 'mortgage', 'most', 'mostly', 'mother', 'motion', 'motivation',
                            'motor', 'mount', 'mountain', 'mouse', 'mouth', 'move', 'movement', 'movie', 'Mr', 'Mrs',
                            'Ms', 'much', 'multiple', 'murder', 'muscle', 'museum', 'music', 'musical', 'musician',
                            'Muslim', 'must', 'mutual', 'my', 'myself', 'mystery', 'myth', 'naked', 'name', 'narrative',
                            'narrow', 'nation', 'national', 'native', 'natural', 'naturally', 'nature', 'near',
                            'nearby', 'nearly', 'necessarily', 'necessary', 'neck', 'need', 'negative', 'negotiate',
                            'negotiation', 'neighbor', 'neighborhood', 'neither', 'nerve', 'nervous', 'net', 'network',
                            'never', 'nevertheless', 'new', 'newly', 'news', 'newspaper', 'next', 'nice', 'night',
                            'nine', 'no', 'nobody', 'nod', 'noise', 'nomination', 'none', 'nonetheless', 'nor',
                            'normal', 'normally', 'north', 'northern', 'nose', 'not', 'note', 'nothing', 'notice',
                            'notion', 'novel', 'now', 'nowhere', 'nuclear', 'number', 'numerous', 'nurse', 'nut',
                            'object', 'objective', 'obligation', 'observation', 'observe', 'observer', 'obtain',
                            'obvious', 'obviously', 'occasion', 'occasionally', 'occupation', 'occupy', 'occur',
                            'ocean', 'odd', 'odds', 'of', 'off', 'offense', 'offensive', 'offer', 'office', 'officer',
                            'official', 'often', 'oh', 'oil', 'ok', 'okay', 'old', 'Olympic', 'on', 'once', 'one',
                            'ongoing', 'onion', 'online', 'only', 'onto', 'open', 'opening', 'operate', 'operating',
                            'operation', 'operator', 'opinion', 'opponent', 'opportunity', 'oppose', 'opposite',
                            'opposition', 'option', 'or', 'orange', 'order', 'ordinary', 'organic', 'organization',
                            'organize', 'orientation', 'origin', 'original', 'originally', 'other', 'others',
                            'otherwise', 'ought', 'our', 'ourselves', 'out', 'outcome', 'outside', 'oven', 'over',
                            'overall', 'overcome', 'overlook', 'owe', 'own', 'owner', 'pace', 'pack', 'package', 'page',
                            'pain', 'painful', 'paint', 'painter', 'painting', 'pair', 'pale', 'Palestinian', 'palm',
                            'pan', 'panel', 'pant', 'paper', 'parent', 'park', 'parking', 'part', 'participant',
                            'participate', 'participation', 'particular', 'particularly', 'partly', 'partner',
                            'partnership', 'party', 'pass', 'passage', 'passenger', 'passion', 'past', 'patch', 'path',
                            'patient', 'pattern', 'pause', 'pay', 'payment', 'PC', 'peace', 'peak', 'peer', 'penalty',
                            'people', 'pepper', 'per', 'perceive', 'percentage', 'perception', 'perfect', 'perfectly',
                            'perform', 'performance', 'perhaps', 'period', 'permanent', 'permission', 'permit',
                            'person', 'personal', 'personality', 'personally', 'personnel', 'perspective', 'persuade',
                            'pet', 'phase', 'phenomenon', 'philosophy', 'phone', 'photo', 'photograph', 'photographer',
                            'phrase', 'physical', 'physically', 'physician', 'piano', 'pick', 'picture', 'pie', 'piece',
                            'pile', 'pilot', 'pine', 'pink', 'pipe', 'pitch', 'place', 'plan', 'plane', 'planet',
                            'planning', 'plant', 'plastic', 'plate', 'platform', 'play', 'player', 'please', 'pleasure',
                            'plenty', 'plot', 'plus', 'PM', 'pocket', 'poem', 'poet', 'poetry', 'point', 'pole',
                            'police', 'policy', 'political', 'politically', 'politician', 'politics', 'poll',
                            'pollution', 'pool', 'poor', 'pop', 'popular', 'population', 'porch', 'port', 'portion',
                            'portrait', 'portray', 'pose', 'position', 'positive', 'possess', 'possibility', 'possible',
                            'possibly', 'post', 'pot', 'potato', 'potential', 'potentially', 'pound', 'pour', 'poverty',
                            'powder', 'power', 'powerful', 'practical', 'practice', 'pray', 'prayer', 'precisely',
                            'predict', 'prefer', 'preference', 'pregnancy', 'pregnant', 'preparation', 'prepare',
                            'prescription', 'presence', 'present', 'presentation', 'preserve', 'president',
                            'presidential', 'press', 'pressure', 'pretend', 'pretty', 'prevent', 'previous',
                            'previously', 'price', 'pride', 'priest', 'primarily', 'primary', 'prime', 'principal',
                            'principle', 'print', 'prior', 'priority', 'prison', 'prisoner', 'privacy', 'private',
                            'probably', 'problem', 'procedure', 'proceed', 'process', 'produce', 'producer', 'product',
                            'production', 'profession', 'professional', 'professor', 'profile', 'profit', 'program',
                            'progress', 'project', 'prominent', 'promise', 'promote', 'prompt', 'proof', 'proper',
                            'properly', 'property', 'proportion', 'proposal', 'propose', 'proposed', 'prosecutor',
                            'prospect', 'protect', 'protection', 'protein', 'protest', 'proud', 'prove', 'provide',
                            'provider', 'province', 'provision', 'psychological', 'psychologist', 'psychology',
                            'public', 'publication', 'publicly', 'publish', 'publisher', 'pull', 'punishment',
                            'purchase', 'pure', 'purpose', 'pursue', 'push', 'put', 'qualify', 'quality', 'quarter',
                            'quarterback', 'question', 'quick', 'quickly', 'quiet', 'quietly', 'quit', 'quite', 'quote',
                            'race', 'racial', 'radical', 'radio', 'rail', 'rain', 'raise', 'range', 'rank', 'rapid',
                            'rapidly', 'rare', 'rarely', 'rate', 'rather', 'rating', 'ratio', 'raw', 'reach', 'react',
                            'reaction', 'read', 'reader', 'reading', 'ready', 'real', 'reality', 'realize', 'really',
                            'reason', 'reasonable', 'recall', 'receive', 'recent', 'recently', 'recipe', 'recognition',
                            'recognize', 'recommend', 'recommendation', 'record', 'recording', 'recover', 'recovery',
                            'recruit', 'red', 'reduce', 'reduction', 'refer', 'reference', 'reflect', 'reflection',
                            'reform', 'refugee', 'refuse', 'regard', 'regarding', 'regardless', 'regime', 'region',
                            'regional', 'register', 'regular', 'regularly', 'regulate', 'regulation', 'reinforce',
                            'reject', 'relate', 'relation', 'relationship', 'relative', 'relatively', 'relax',
                            'release', 'relevant', 'relief', 'religion', 'religious', 'rely', 'remain', 'remaining',
                            'remarkable', 'remember', 'remind', 'remote', 'remove', 'repeat', 'repeatedly', 'replace',
                            'reply', 'report', 'reporter', 'represent', 'representation', 'representative',
                            'Republican', 'reputation', 'request', 'require', 'requirement', 'research', 'researcher',
                            'resemble', 'reservation', 'resident', 'resist', 'resistance', 'resolution', 'resolve',
                            'resort', 'resource', 'respect', 'respond', 'respondent', 'response', 'responsibility',
                            'responsible', 'rest', 'restaurant', 'restore', 'restriction', 'result', 'retain', 'retire',
                            'retirement', 'return', 'reveal', 'revenue', 'review', 'revolution', 'rhythm', 'rice',
                            'rich', 'rid', 'ride', 'rifle', 'right', 'ring', 'rise', 'risk', 'river', 'road', 'rock',
                            'role', 'roll', 'romantic', 'roof', 'room', 'root', 'rope', 'rose', 'rough', 'roughly',
                            'round', 'route', 'routine', 'row', 'rub', 'rule', 'run', 'running', 'rural', 'rush',
                            'Russian', 'sacred', 'sad', 'safe', 'safety', 'sake', 'salad', 'salary', 'sale', 'sales',
                            'salt', 'same', 'sample', 'sanction', 'sand', 'satellite', 'satisfaction', 'satisfy',
                            'sauce', 'save', 'saving', 'say', 'scale', 'scandal', 'scared', 'scenario', 'scene',
                            'schedule', 'scheme', 'scholar', 'scholarship', 'school', 'science', 'scientific',
                            'scientist', 'scope', 'score', 'scream', 'screen', 'script', 'sea', 'search', 'season',
                            'seat', 'second', 'secret', 'secretary', 'section', 'sector', 'secure', 'security', 'see',
                            'seed', 'seek', 'seem', 'segment', 'seize', 'select', 'selection', 'self', 'sell', 'Senate',
                            'senator', 'send', 'senior', 'sense', 'sensitive', 'sentence', 'separate', 'sequence',
                            'series', 'serious', 'seriously', 'serve', 'service', 'session', 'set', 'setting', 'settle',
                            'settlement', 'seven', 'several', 'severe', 'sex', 'sexual', 'shade', 'shadow', 'shake',
                            'shall', 'shape', 'share', 'sharp', 'she', 'sheet', 'shelf', 'shell', 'shelter', 'shift',
                            'shine', 'ship', 'shirt', 'shit', 'shock', 'shoe', 'shoot', 'shooting', 'shop', 'shopping',
                            'shore', 'short', 'shortly', 'shot', 'should', 'shoulder', 'shout', 'show', 'shower',
                            'shrug', 'shut', 'sick', 'side', 'sigh', 'sight', 'sign', 'signal', 'significance',
                            'significant', 'significantly', 'silence', 'silent', 'silver', 'similar', 'similarly',
                            'simple', 'simply', 'sin', 'since', 'sing', 'singer', 'single', 'sink', 'sir', 'sister',
                            'sit', 'site', 'situation', 'six', 'size', 'ski', 'skill', 'skin', 'sky', 'slave', 'sleep',
                            'slice', 'slide', 'slight', 'slightly', 'slip', 'slow', 'slowly', 'small', 'smart', 'smell',
                            'smile', 'smoke', 'smooth', 'snap', 'snow', 'so', 'so-called', 'soccer', 'social',
                            'society', 'soft', 'software', 'soil', 'solar', 'soldier', 'solid', 'solution', 'solve',
                            'some', 'somebody', 'somehow', 'someone', 'something', 'sometimes', 'somewhat', 'somewhere',
                            'son', 'song', 'soon', 'sophisticated', 'sorry', 'sort', 'soul', 'sound', 'soup', 'source',
                            'south', 'southern', 'Soviet', 'space', 'Spanish', 'speak', 'speaker', 'special',
                            'specialist', 'species', 'specific', 'specifically', 'speech', 'speed', 'spend', 'spending',
                            'spin', 'spirit', 'spiritual', 'split', 'spokesman', 'sport', 'spot', 'spread', 'spring',
                            'square', 'squeeze', 'stability', 'stable', 'staff', 'stage', 'stair', 'stake', 'stand',
                            'standard', 'standing', 'star', 'stare', 'start', 'state', 'statement', 'station',
                            'statistics', 'status', 'stay', 'steady', 'steal', 'steel', 'step', 'stick', 'still',
                            'stir', 'stock', 'stomach', 'stone', 'stop', 'storage', 'store', 'storm', 'story',
                            'straight', 'strange', 'stranger', 'strategic', 'strategy', 'stream', 'street', 'strength',
                            'strengthen', 'stress', 'stretch', 'strike', 'string', 'strip', 'stroke', 'strong',
                            'strongly', 'structure', 'struggle', 'student', 'studio', 'study', 'stuff', 'stupid',
                            'style', 'subject', 'submit', 'subsequent', 'substance', 'substantial', 'succeed',
                            'success', 'successful', 'successfully', 'such', 'sudden', 'suddenly', 'sue', 'suffer',
                            'sufficient', 'sugar', 'suggest', 'suggestion', 'suicide', 'suit', 'summer', 'summit',
                            'sun', 'super', 'supply', 'support', 'supporter', 'suppose', 'supposed', 'Supreme', 'sure',
                            'surely', 'surface', 'surgery', 'surprise', 'surprised', 'surprising', 'surprisingly',
                            'surround', 'survey', 'survival', 'survive', 'survivor', 'suspect', 'sustain', 'swear',
                            'sweep', 'sweet', 'swim', 'swing', 'switch', 'symbol', 'symptom', 'system', 'table',
                            'tablespoon', 'tactic', 'tail', 'take', 'tale', 'talent', 'talk', 'tall', 'tank', 'tap',
                            'tape', 'target', 'task', 'taste', 'tax', 'taxpayer', 'tea', 'teach', 'teacher', 'teaching',
                            'team', 'tear', 'teaspoon', 'technical', 'technique', 'technology', 'teen', 'teenager',
                            'telephone', 'telescope', 'television', 'tell', 'temperature', 'temporary', 'ten', 'tend',
                            'tendency', 'tennis', 'tension', 'tent', 'term', 'terms', 'terrible', 'territory', 'terror',
                            'terrorism', 'terrorist', 'test', 'testify', 'testimony', 'testing', 'text', 'than',
                            'thank', 'thanks', 'that', 'the', 'theater', 'their', 'them', 'theme', 'themselves', 'then',
                            'theory', 'therapy', 'there', 'therefore', 'these', 'they', 'thick', 'thin', 'thing',
                            'think', 'thinking', 'third', 'thirty', 'this', 'those', 'though', 'thought', 'thousand',
                            'threat', 'threaten', 'three', 'throat', 'through', 'throughout', 'throw', 'thus', 'ticket',
                            'tie', 'tight', 'time', 'tiny', 'tip', 'tire', 'tired', 'tissue', 'title', 'to', 'tobacco',
                            'today', 'toe', 'together', 'tomato', 'tomorrow', 'tone', 'tongue', 'tonight', 'too',
                            'tool', 'tooth', 'top', 'topic', 'toss', 'total', 'totally', 'touch', 'tough', 'tour',
                            'tourist', 'tournament', 'toward', 'towards', 'tower', 'town', 'toy', 'trace', 'track',
                            'trade', 'tradition', 'traditional', 'traffic', 'tragedy', 'trail', 'train', 'training',
                            'transfer', 'transform', 'transformation', 'transition', 'translate', 'transportation',
                            'travel', 'treat', 'treatment', 'treaty', 'tree', 'tremendous', 'trend', 'trial', 'tribe',
                            'trick', 'trip', 'troop', 'trouble', 'truck', 'true', 'truly', 'trust', 'truth', 'try',
                            'tube', 'tunnel', 'turn', 'TV', 'twelve', 'twenty', 'twice', 'twin', 'two', 'type',
                            'typical', 'typically', 'ugly', 'ultimate', 'ultimately', 'unable', 'uncle', 'under',
                            'undergo', 'understand', 'understanding', 'unfortunately', 'uniform', 'union', 'unique',
                            'unit', 'United', 'universal', 'universe', 'university', 'unknown', 'unless', 'unlike',
                            'unlikely', 'until', 'unusual', 'up', 'upon', 'upper', 'urban', 'urge', 'us', 'use', 'used',
                            'useful', 'user', 'usual', 'usually', 'utility', 'vacation', 'valley', 'valuable', 'value',
                            'variable', 'variation', 'variety', 'various', 'vary', 'vast', 'vegetable', 'vehicle',
                            'venture', 'version', 'versus', 'very', 'vessel', 'veteran', 'via', 'victim', 'victory',
                            'video', 'view', 'viewer', 'village', 'violate', 'violation', 'violence', 'violent',
                            'virtually', 'virtue', 'virus', 'visible', 'vision', 'visit', 'visitor', 'visual', 'vital',
                            'voice', 'volume', 'volunteer', 'vote', 'voter', 'vs', 'vulnerable', 'wage', 'wait', 'wake',
                            'walk', 'wall', 'wander', 'want', 'war', 'warm', 'warn', 'warning', 'wash', 'waste',
                            'watch', 'water', 'wave', 'way', 'we', 'weak', 'wealth', 'wealthy', 'weapon', 'wear',
                            'weather', 'wedding', 'week', 'weekend', 'weekly', 'weigh', 'weight', 'welcome', 'welfare',
                            'well', 'west', 'western', 'wet', 'what', 'whatever', 'wheel', 'when', 'whenever', 'where',
                            'whereas', 'whether', 'which', 'while', 'whisper', 'white', 'who', 'whole', 'whom', 'whose',
                            'why', 'wide', 'widely', 'widespread', 'wife', 'wild', 'will', 'willing', 'win', 'wind',
                            'window', 'wine', 'wing', 'winner', 'winter', 'wipe', 'wire', 'wisdom', 'wise', 'wish',
                            'with', 'withdraw', 'within', 'without', 'witness', 'woman', 'wonder', 'wonderful', 'wood',
                            'wooden', 'word', 'work', 'worker', 'working', 'works', 'workshop', 'world', 'worried',
                            'worry', 'worth', 'would', 'wound', 'wrap', 'write', 'writer', 'writing', 'wrong', 'yard',
                            'yeah', 'year', 'yell', 'yellow', 'yes', 'yesterday', 'yet', 'yield', 'you', 'young',
                            'your', 'yours', 'yourself', 'youth', 'zone'}

    # User agent list
    USER_AGENT_LIST = [
        "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; fi-fi) AppleWebKit/420+ (KHTML, like Gecko) Safari/419.3",
        "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; de-de) AppleWebKit/125.2 (KHTML, like Gecko) Safari/125.7",
        "Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-us) AppleWebKit/312.8 (KHTML, like Gecko) Safari/312.6",
        "Mozilla/5.0 (Windows; U; Windows NT 5.1; cs-CZ) AppleWebKit/523.15 (KHTML, like Gecko) Version/3.0 Safari/523.15",
        "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/528.16 (KHTML, like Gecko) Version/4.0 Safari/528.16",
        "Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_6; it-it) AppleWebKit/528.16 (KHTML, like Gecko) Version/4.0 Safari/528.16",
        "Mozilla/5.0 (Windows; U; Windows NT 6.1; zh-HK) AppleWebKit/533.18.1 (KHTML, like Gecko) Version/5.0.2 Safari/533.18.5",
        "Mozilla/5.0 (Windows; U; Windows NT 6.1; sv-SE) AppleWebKit/533.19.4 (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4",
        "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/536.26.17 (KHTML, like Gecko) Version/6.0.2 Safari/536.26.17",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/6.1.3 Safari/537.75.14",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/600.3.10 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.10",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.39 (KHTML, like Gecko) Version/9.0 Safari/601.1.39",
        "Mozilla/5.0 (Linux; U; Android 1.5; de-de; HTC Magic Build/CRB17) AppleWebKit/528.5+ (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1",
        "Mozilla/5.0 (Linux; U; Android 2.1-update1; en-au; HTC_Desire_A8183 V1.16.841.1 Build/ERE27) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17",
        "Mozilla/5.0 (Linux; U; Android 4.2; en-us; Nexus 10 Build/JVP15I) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30",
        "Mozilla/5.0 (Linux; U; Android-4.0.3; en-us; Galaxy Nexus Build/IML74K) AppleWebKit/535.7 (KHTML, like Gecko) CrMo/16.0.912.75 Mobile Safari/535.7",
        "Mozilla/5.0 (Linux; U; Android-4.0.3; en-us; Xoom Build/IML77) AppleWebKit/535.7 (KHTML, like Gecko) CrMo/16.0.912.75 Safari/535.7",
        "Mozilla/5.0 (Linux; Android 4.0.4; SGH-I777 Build/Task650 & Ktoonsez AOKP) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19",
        "Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus Build/JRN84D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19",
        "Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_1_1 like Mac OS X; en) AppleWebKit/534.46.0 (KHTML, like Gecko) CriOS/19.0.1084.60 Mobile/9B206 Safari/7534.48.3",
        "Mozilla/5.0 (iPad; U; CPU OS 5_1_1 like Mac OS X; en-us) AppleWebKit/534.46.0 (KHTML, like Gecko) CriOS/19.0.1084.60 Mobile/9B206 Safari/7534.48.3",
        "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Ubuntu/10.10 Chromium/8.0.552.237 Chrome/8.0.552.237 Safari/534.10",
        "Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.7 (KHTML, like Gecko) Ubuntu/11.10 Chromium/16.0.912.21 Chrome/16.0.912.21 Safari/535.7",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.2 (KHTML, like Gecko) Ubuntu/11.04 Chromium/15.0.871.0 Chrome/15.0.871.0 Safari/535.2",
        "Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.1 (KHTML, like Gecko) Ubuntu/10.04 Chromium/14.0.813.0 Chrome/14.0.813.0 Safari/535.1",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Ubuntu/10.10 Chromium/12.0.742.112 Chrome/12.0.742.112 Safari/534.30",
        "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Ubuntu/10.10 Chromium/8.0.552.237 Chrome/8.0.552.237 Safari/534.10",
        "Mozilla/5.0 (Windows; U; Windows NT 5.0; it-IT; rv:1.7.12) Gecko/20050915",
        "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.0.1) Gecko/20020919",
        "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1b2pre) Gecko/20081015 Fennec/1.0a1",
        "Mozilla/5.0 (X11; U; Linux armv7l; en-US; rv:1.9.2a1pre) Gecko/20090322 Fennec/1.0b2pre",
        "Mozilla/5.0 (Android; Linux armv7l; rv:9.0) Gecko/20111216 Firefox/9.0 Fennec/9.0",
        "Mozilla/5.0 (Android; Mobile; rv:12.0) Gecko/12.0 Firefox/12.0",
        "Mozilla/5.0 (Android; Mobile; rv:14.0) Gecko/14.0 Firefox/14.0",
        "Mozilla/5.0 (Mobile; rv:14.0) Gecko/14.0 Firefox/14.0",
        "Mozilla/5.0 (Mobile; rv:17.0) Gecko/17.0 Firefox/17.0",
        "Mozilla/5.0 (Tablet; rv:18.1) Gecko/18.1 Firefox/18.1",
        "Mozilla/5.0 (Android; Mobile; rv:28.0) Gecko/28.0 Firefox/28.0",
        "Mozilla/5.0 (Android; Tablet; rv:29.0) Gecko/29.0 Firefox/29.0",
        "Mozilla/5.0 (Android; Mobile; rv:40.0) Gecko/40.0 Firefox/40.0",
        "Mozilla/5.0 (iPad; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4",
        "Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.5) Gecko/20031007 Firebird/0.7",
        "Mozilla/5.0 (Windows; U; Win95; en-US; rv:1.5) Gecko/20031007 Firebird/0.7",
        "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3) Gecko/20090305 Firefox/3.1b3 GTB5",
        "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; ko; rv:1.9.1b2) Gecko/20081201 Firefox/3.1b2",
        "Mozilla/5.0 (X11; U; SunOS sun4u; en-US; rv:1.9b5) Gecko/2008032620 Firefox/3.0b5",
        "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.12) Gecko/20080214 Firefox/2.0.0.12",
        "Mozilla/5.0 (Windows; U; Windows NT 5.1; cs; rv:1.9.0.8) Gecko/2009032609 Firefox/3.0.8",
        "Mozilla/5.0 (X11; U; OpenBSD i386; en-US; rv:1.8.0.5) Gecko/20060819 Firefox/1.5.0.5",
        "Mozilla/5.0 (Windows; U; Windows NT 5.0; es-ES; rv:1.8.0.3) Gecko/20060426 Firefox/1.5.0.3",
        "Mozilla/5.0 (Windows; U; WinNT4.0; en-US; rv:1.7.9) Gecko/20050711 Firefox/1.0.5",
        "Mozilla/5.0 (Windows; Windows NT 6.1; rv:2.0b2) Gecko/20100720 Firefox/4.0b2",
        "Mozilla/5.0 (X11; Linux x86_64; rv:2.0b4) Gecko/20100818 Firefox/4.0b4",
        "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2) Gecko/20100308 Ubuntu/10.04 (lucid) Firefox/3.6 GTB7.1",
        "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:2.0b7) Gecko/20101111 Firefox/4.0b7",
        "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:2.0b8pre) Gecko/20101114 Firefox/4.0b8pre",
        "Mozilla/5.0 (X11; Linux x86_64; rv:2.0b9pre) Gecko/20110111 Firefox/4.0b9pre",
        "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:2.0b9pre) Gecko/20101228 Firefox/4.0b9pre",
        "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:2.2a1pre) Gecko/20110324 Firefox/4.2a1pre",
        "Mozilla/5.0 (X11; U; Linux amd64; rv:5.0) Gecko/20100101 Firefox/5.0 (Debian)",
        "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:6.0a2) Gecko/20110613 Firefox/6.0a2",
        "Mozilla/5.0 (X11; Linux i686 on x86_64; rv:12.0) Gecko/20100101 Firefox/12.0",
        "Mozilla/5.0 (Windows NT 6.1; rv:15.0) Gecko/20120716 Firefox/15.0a2",
        "Mozilla/5.0 (X11; Ubuntu; Linux armv7l; rv:17.0) Gecko/20100101 Firefox/17.0",
        "Mozilla/5.0 (Windows NT 6.1; rv:21.0) Gecko/20130328 Firefox/21.0",
        "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:22.0) Gecko/20130328 Firefox/22.0",
        "Mozilla/5.0 (Windows NT 5.1; rv:25.0) Gecko/20100101 Firefox/25.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:25.0) Gecko/20100101 Firefox/25.0",
        "Mozilla/5.0 (Windows NT 6.1; rv:28.0) Gecko/20100101 Firefox/28.0",
        "Mozilla/5.0 (X11; Linux i686; rv:30.0) Gecko/20100101 Firefox/30.0",
        "Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0",
        "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0",
        "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0",
        "Mozilla/5.0 (BeOS; U; Haiku BePC; en-US; rv:1.8.1.21pre) Gecko/20090227 BonEcho/2.0.0.21pre",
        "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.9) Gecko/20071113 BonEcho/2.0.0.9",
        "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1) Gecko/20061026 BonEcho/2.0",
        "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko/2009033017 GranParadiso/3.0.8",
        "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2) Gecko/20100411 Lorentz/3.6.3 GTB7.0",
        "Mozilla/5.0 (X11; U; Linux i686; it; rv:1.9.3a1pre) Gecko/20091019 Minefield/3.7a1pre",
        "Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.9.3a4pre) Gecko/20100402 Minefield/3.7a4pre",
        "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2a2pre) Gecko/20090901 Ubuntu/9.10 (karmic) Namoroka/3.6a2pre",
        "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2a1) Gecko/20090806 Namoroka/3.6a1",
        "Mozilla/5.0 (Windows; U; Windows NT 6.1; cs; rv:1.9.2a2pre) Gecko/20090912 Namoroka/3.6a2pre (.NET CLR 3.5.30729)",
        "Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1b3pre) Gecko/20090109 Shiretoko/3.1b3pre",
        "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.1b4pre) Gecko/20090311 Shiretoko/3.1b4pre",
        "Opera/5.11 (Windows 98; U) [en]",
        "Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 5.12 [en]",
        "Opera/6.0 (Windows 2000; U) [fr]",
        "Mozilla/4.0 (compatible; MSIE 5.0; Windows NT 4.0) Opera 6.01 [en]",
        "Opera/7.03 (Windows NT 5.0; U) [en]",
        "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.10 [en]",
        "Opera/9.02 (Windows XP; U; ru)",
        "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.24",
        "Opera/9.51 (Macintosh; Intel Mac OS X; U; en)",
        "Opera/9.70 (Linux i686 ; U; en) Presto/2.2.1",
        "Opera/9.80 (Windows NT 5.1; U; cs) Presto/2.2.15 Version/10.00",
        "Opera/9.80 (Windows NT 6.1; U; sv) Presto/2.7.62 Version/11.01",
        "Opera/9.80 (Windows NT 6.1; U; en-GB) Presto/2.7.62 Version/11.00",
        "Opera/9.80 (Windows NT 6.1; U; zh-tw) Presto/2.7.62 Version/11.01",
        "Opera/9.80 (Windows NT 6.0; U; en) Presto/2.8.99 Version/11.10",
        "Opera/9.80 (X11; Linux i686; U; ru) Presto/2.8.131 Version/11.11",
        "Opera/9.80 (Windows NT 5.1) Presto/2.12.388 Version/12.14",
        "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.12 Safari/537.36 OPR/14.0.1116.4",
        "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.29 Safari/537.36 OPR/15.0.1147.24 (Edition Next)",
        "Opera/9.80 (Linux armv6l ; U; CE-HTML/1.0 NETTV/3.0.1;; en) Presto/2.6.33 Version/10.60",
        "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36 OPR/20.0.1387.91",
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Oupeng/10.2.1.86910 Safari/534.30",
        "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2376.0 Safari/537.36 OPR/31.0.1857.0",
        "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36 OPR/32.0.1948.25"
    ]
